### ISSUE TITLE
2차 리팩토링

### ISSUE THREAD

**Issue by kitaee** [telling-me/tellingme-server#101]
### 📃 Description
코드가 너무 꼬여버렸어 ㅠ

### ✔ Todo
- [x] AnswerService에 주입받는 것들에서 Service 없애기 (ex.. communicationService) -> 나중에 순환장애 우려
- [x] LocalDateTime.now(ZoneId.of("Asia/Seoul")) -> PostConstruct 등 전역적으로 선언할 수 있는 방법 찾기
- [x] 테스트 서버 및 DB 구축
- [x] Communication 객체 생성 시, 조금 더 재사용성 있게 만들기 -> 예를 들어 지금은 생성할 때 likeCount를 바로 0으로 박는데 충분히 수정이 가능한 곳이여서 기존의 answer.getLikeCount 이런식으로 가져오는게 더 좋을 것 같음
- [x] 생각나면 계속 추가 예정

### 🔴 ETC
예상 개발 기간: 꽤 걸릴듯.?

**Comment by SL313** [comment]
2차 리팩토링 시급 ...
오늘 테스트 서버 환경 구축하고 내일부터 해커톤 전까지는 리팩토링...?
해커톤 때는 3차 기능 개발!
