### ISSUE TITLE
대규모 리팩토링 

### ISSUE THREAD

**Issue by kitaee** [telling-me/tellingme-server#129]
### 📃 Description
마케팅에 들어가기 전, 대규모 리팩토링 (코드 정리 및 서버 구조 변경)

### ✔ Todo
- [ ] 서버 구조 변경 (기존 1개 운영서버 -> 2개의 운영서버 + 로드밸런싱) // 담당자 : 미정
- [ ] 푸시알림, 알림창 등 단순 String 부분 -> Enum으로 변경 // 담당자 : 기태
- [ ] 폴더구조 변경 // 담당자 : 미정
- [ ] 스프링 시큐리티 Authorization 도입 // 담당자 : 기태
- [ ] Controller ResponeEntity 와일드카드 타입 사용 금지 // 담당자 : 미정
- [ ] 감정, 신고 사유 등 인덱스 통일 // 담당자 : 예빈
- [ ] Service 결합도 수정 -> component화 // 담당자 : 예빈
- [ ] Junit, MockMvc등 테스트케이스 도입 // 담당자 : 기태, 예빈

### 🔴 ETC
예상 개발 기간: 약 2주
