### ISSUE TITLE
회원가입 추가정보 입력 절차 (1)

### ISSUE THREAD

**Issue by SL313** [telling-me/tellingme-server#15]
### 📃 Description
회원가입 추가정보
- 닉네임 (최소 2글자 최대 8글자) <중복 불가>
- 성별
- 생년월일
- 고민 (기타 입력 불가) <최대 2가지 선택 가능>
- 직업 (기타 입력 가능)
- mbti
- 푸시 알림 허용 여부

### ✔ Todo
- [x] user domain 정리
- [x] user dto 정리
- [x] service 단 로직 작성
- [x] api test

### 🔴 ETC
기타 사항을 적어주세요.
예상 개발 기간: 3시간

**우선 만들어서 api test까지 해보고, 리팩토링
