### ISSUE TITLE
회원가입 추가정보 입력 절차 (2)

### ISSUE THREAD

**Issue by SL313** [telling-me/tellingme-server#17]
### 📃 Description
아직 예외처리 안 된 부분
1. 애플 지침에 따라 업데이트 된 정보들 중에 필수 -> 선택 으로 변경되는 것 (성별, 생년월일)
2. 닉네임 영문, 숫자, 특수기호, 띄어쓰기, 욕설 불가하게 설정
3. 직업 '기타' 선택 후 직접 입력 시 저장할 table 생성 및 저장할 로직 구현

회원가입 추가정보
- 닉네임 (최소 2글자 최대 8글자) <중복 불가>
- 성별
- 생년월일
- 고민 (기타 입력 불가) <최대 2가지 선택 가능>
- 직업 (기타 입력 가능)
- mbti
- 푸시 알림 허용 여부

### ✔ Todo
- [x] 닉네임 영문, 숫자, 특수기호 불가
- [x] 닉네임 띄어쓰기 불가
- [x] 닉네임 욕설 불가
- [x] 직업 (기타) 정보 저장 table 설계 및 생성
- [x] 직업 (기타) 정보 받아오는 로직 구현
- [x] 회원가입 정보 필수 -> 선택 변경되는 [성별, 생년월일] 수정

### 🔴 ETC
기타 사항을 적어주세요.
예상 개발 기간: 일주일
