### ISSUE TITLE
token 관리 구현

### ISSUE THREAD

**Issue by SL313** [telling-me/tellingme-server#42]
### 📃 Description
apple token parser 수정

### ✔ Todo
- [x] Optional 반환형 수정
- [x] socialId 로직 수정
- [ ] 토큰 parsing 로직 전체 리팩토링

### 🔴 ETC
기타 사항을 적어주세요.
예상 개발 기간: 1시간
