### ISSUE TITLE
해결해야 될 오류 리스트

### ISSUE THREAD

**Issue by SL313** [telling-me/tellingme-server#60]
### 📃 Description
해결해야 될 오류 리스트
(https만큼 급하지는 않지만 급함! ㅎㅋ 1차 배포 전까지 무조건 해결해야 됨 !! ~~)

### ✔ Todo
- [x] 이메일 api 오류 수정 (구글 셋팅 다시하기)
- [x] 방화벽 체크 XSS
- [x] git branch 삭제 및 정리

### 🔴 ETC
기타 사항을 적어주세요.
예상 개발 기간:
